### PR TITLE
Extract nascent/unprocessed transcripts (i.e. the entire gene)

### PR DESCRIPTION
**Pull request by Yenaled**

### CODE REVIEW

**Comment by Yenaled** [comment]
@Lioscro I desperately needed a feature to extract unprocessed/nascent transcripts (i.e. the entire gene) for kb-python purposes. Can you review and update ngs-tools asap?

**Comment by Lioscro** [comment]
How are you planning on using this? If your goal is to install this version into your version of kb-python for testing purposes, you can always just replace the `ngs-tools` line in the `requirements.txt` to point at your branch instead
```
git+https://github.com/Yenaled/ngs-tools@patch-1
```
and then just `pip install .`

**Comment by Yenaled** [comment]
Will write a small test in a bit! However, this will eventually become part of the next release of kallisto bustools and I can't release the next version of kallisto until I have this workflow in place. It's absolutely essential for single-nucleus quantification (--workflow nucleus) and for similar analyses like RNA velocity.

On a similar note, I'll be making some big changes to kb-python in the near future and changing some defaults (since Kristjan and I essentially rewrote the entire kallisto engine) -- when I make a pull request for them, please review my code and tell me what tests I should write.

**Comment by Yenaled** [comment]
@Lioscro I think I added all the testing correctly. Please run the tests and, if all good, update it. :)

**Pull request merged**
